POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhYnJhbW92IiwiaWQiOiI1ZDIyMTUxYzk3YzYxZTM1Njc4ZTBiMmMiLCJpYXQiOjE1NjI2MTI3OTZ9.bcRoi7bgOdMyANUJdsPVSBopaw7xN0jq6ODhNQV5eHI

{
  "title": "Saving Money on Energy Bills",
  "author": "Miss Thrifty",
  "url": "https://www.miss-thrifty.co.uk/the-mythbusters-guide-to-saving-money-on-energy-bills/"
}